version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: std_ghibli_db
      POSTGRES_USER: harngalf
      POSTGRES_PASSWORD: A142536
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80