version: '3.3'

services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   env_file: .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./webapp:/opt/webapp
  
  
  
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    depends_on:
      - postgres
    ports:
      - 8000:8000

    

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: std_ghibli_db
      POSTGRES_USER: harngalf
      POSTGRES_PASSWORD: A142536
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - 5050:80